### ISSUE TITLE
Task view v2

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/vara#100]
Task view tasks:

Display only feedback of how many students solved with how many attempemts:
[number of students] (N%) õpilast lahendas ülesande korrektselt esimese korraga, [number of students] (N%) õpilast lahendas ülesande vähemalt ühel korral õigesti, [number of students] (N%) õpilast ei saanud ühegi katsega õiget vastust

In case FLT (or any of sub-elements) existing for tasks, display general feedback:

 
![dash-vara](https://user-images.githubusercontent.com/380007/229494371-281ef297-b290-4802-9546-f87d2567fcaa.png)

**Comment by pjotrsavitski** [comment]
Kas FLT puhul poleks parem muuta visuaali nii, et iga täht oleks omaette vajutatav element. Selle peale vajutades avaneks dialoog ning kuvaks vastavat kirjeldust?
