### ISSUE TITLE
Extra profile fields for Teacher and Student

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/vara#12]
Add additional fields for profiles (if not existing):

**Taecher:**
Full name
E-mail
School (drop-down)
Class (1-12)
Subject (drop-down)

**Student:**
Full name
E-mail
School (drop-down)
Class (1-12)

**Comment by pankajchejara23** [comment]
Two extra roles created: Teacher and Student. 
Fields added to Student role: full name, class, school, email
Fields added to Teacher role: full name, class, subject, school, email

![Extra_profile_add](https://user-images.githubusercontent.com/21138354/199434561-1751ee2f-61cc-4e50-a848-5d17d0d8fd8f.gif)
