### ISSUE TITLE
Teachers are able to see detailed progress of the Students

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/vara#121]
Clicking on a single task marker opens a pop-up containg following information (if exists):

(Wrong answer) - First and Last Name did not aswer correctly (an options's content) + timestamp
(Opened a hint) - First and Last Name opened a hind "Hint text" + timestamp
(Correct answer) - First and Last Name answered correctly (an options's content) + timestamp 

![2023-05-12 14 13 55](https://github.com/centre-for-educational-technology/vara/assets/380007/b6b6c8f0-eff5-4f2f-9727-ecb9c2e199b8)

**Comment by pjotrsavitski** [comment]
I'd say this has been implemented and tested.
