### ISSUE TITLE
Add new taxonomy: FLT (ENG Mathematical thinking / EST Matemaatiline mõtlemine)

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/vara#36]
- [x]  Add new taxonomy (FLT)
- [x]  Users are able to tag learning materials using FLT taxonomy (users can set one or more second level items for the material, e.g. F2, F3 and L1)

F
-- F1
-- F2
-- F3

L
-- L1
-- L2
-- L3

T
-- T1
-- T2
-- T3

**Comment by pjotrsavitski** [comment]
I propose that we use [this](https://www.drupal.org/project/term_reference_tree) widget for that. It allows serious configurations with only allowing to select leaf values and much more.
