### ISSUE TITLE
All H5P resources are available only for logged-in users

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/vara#48]

**Comment by pjotrsavitski** [comment]
We will need to decide something about the search page as it displays a full view.
I see two different solutions:
* change the search to only display simple view with the title
* make search only accessible to authenticated users

@tammets Which one would you choose?

**Comment by pjotrsavitski** [comment]
We will start with teaser view for anonymous users and full view for authenticated ones. If that causes issues in future, then we will need to find a different solution.
