### ISSUE TITLE
Missing user credentials in xAPI statements

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/vara#49]
User data is not sent with xapi statements even if the user is logged in (node & embed view).

![Screenshot 2023-01-17 at 11 40 45](https://user-images.githubusercontent.com/380007/212872548-10312965-46ca-4e91-b6e1-6d4d7dde918f.png)

**Comment by pjotrsavitski** [comment]
This one is really due to a cache problem that caches the H5PIntegration JS data and uses that for multiple different users (also mixing together authenticated and unauthenticated users).

**Comment by pjotrsavitski** [comment]
We now have caches disabled for both material view (on field formatter level) and embed view for H5P content. This is the best solution we can come up with at the moment, but the real solution would be to work with the Joubel team and find a way to make sure that just the H5PIntegration part will never be cached.
